---
- name: Kibana Configure file transfer.
  template:
    src: 'kibana.yml.j2'
    dest: '/etc/kibana/kibana.yml'
    backup: 'yes'
    owner: 'kibana'
    group: 'kibana'
    mode: '0640'
  register: kibana_config

- name: Increased the Kibana heap size.
  lineinfile:
    state: 'present'
    dest: '{{ item }}'
    regexp: '^NODE_OPTIONS'
    line: 'NODE_OPTIONS="--max-old-space-size=4096"'
  loop:
    - '/etc/sysconfig/kibana'
    - '/etc/default/kibana'
  register: kibana_heap
  changed_when: false
  failed_when: false
