---
- name: Kibana Configure file transfer
  template:
    src: 'kibana.yml.j2'
    dest: '/etc/kibana/kibana.yml'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: kibana_config
