---
- name: Kibana exporter program binary transfer.
  unarchive:
    src: 'kibana_exporter.tar.xz'
    dest: '/usr/local/bin'
    owner: 'kibana'
    group: 'kibana'
    mode: '0755'
  notify: 'Ensure Kibana exporter service is enabled.'

- name: Kibana exporter configure file transfer.
  template:
    src: 'kibana_exporter.default.j2'
    dest: '/etc/default/kibana_exporter'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Ensure Kibana exporter service is enabled.'

- name: Kibana service file transfer.
  copy:
    src: 'kibana_exporter.service'
    dest: '/lib/systemd/system'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'Ensure Kibana exporter service is enabled.'