---
- name: Kibana exporter program binary transfer.
  unarchive:
    src: 'kibana_exporter.tar.xz'
    dest: '/usr/local/bin'
    owner: 'kibana'
    group: 'kibana'
    mode: '0755'
  register: kibana_exporter_update

- name: Kibana exporter configure file transfer.
  template:
    src: 'kibana_exporter.default.j2'
    dest: '/etc/default/kibana_exporter'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: kibana_exporter_config

- name: Kibana service file transfer.
  copy:
    src: 'kibana_exporter.service'
    dest: '/lib/systemd/system'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: kibana_systemd_update

- name: Reloading the Kibana exporter service.
  systemd:
    name: 'kibana_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  when: kibana_exporter_update is changed or kibana_exporter_config is changed or kibana_systemd_update is changed
