---
- name: Gather Kibana node variables for cluster
  set_fact:
    kibana_servers: "\
      {% set _kibana_servers = [] %}\
      {% for host in groups[group_names[-1]] %}\
        {% if ( kibana_is_install ) %}\
          {% if _kibana_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
        {% endif %}\
      {% endfor %}\
      {{ _kibana_servers }}"
  when: kibana_servers is not defined

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status
  include: 'selinux.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Configuration the elasticsearch
  include: 'configureation.yml'

- name: Include plugins tasks
  include: 'plugins.yml'
  when: kibana_plugins is defined

- name: Reload the Kibana service
  shell: echo ''
  notify: 'Ensure Kibana service is enabled'
  when: kibana_config is changed or kibana_update is changed or kibana_plugin is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Registered with HashiCorp Consul # Not available in basic authentication mode.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool
    - not kibana_auth | bool
