---
- name: Gather Kibana node variables for cluster.
  set_fact:
    kibana_servers: "\
      {% set _kibana_servers = [] %}\
      {% for host in groups[group_names[0]] %}\
        {% if ( kibana_is_install ) %}\
          {% if _kibana_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
        {% endif %}\
      {% endfor %}\
      {{ _kibana_servers }}"
  when: kibana_servers is not defined

- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Configuration the kibana.
  include: 'configureation.yml'

- name: Include certificate tasks.
  include: 'certificates.yml'
  when: kibana_https | bool

- name: Ensure directory permissions.
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: 'kibana'
    group: 'kibana'
    mode: '0755'
    recurse: 'yes'
  loop:
    - '/usr/share/kibana/optimize'
    - '/usr/share/kibana/plugins'

- name: Include plugins tasks.
  include: 'plugins.yml'

- name: Include prometheus exporter tasks.
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Reload the Kibana service.
  shell: echo ''
  notify: 'Ensure Kibana service is enabled'
  when: kibana_config is changed or kibana_update is changed or kibana_plugin is changed or kibana_heap is changed

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool
    - kibana_prometheus_plugin is succeeded
