---
- name: Install kibana plugins.
  shell: >-
    NODE_OPTIONS="--no-warnings --max-old-space-size=4096" /usr/share/kibana/bin/kibana-plugin install
    {{ item }}
  args:
    executable: '/bin/bash'
    chdir: '/usr/share/kibana'
  become: 'yes'
  become_user: 'kibana'
  register: kibana_plugin
  until: kibana_plugin is succeeded
  retries: 5
  delay: 2
  loop: '{{ kibana_plugins | default({}) | list }}'
  changed_when: false
  failed_when: false
