---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add Kibana YUM repositories.
  yum_repository:
    name: '{{ kibana_repo_name }}'
    description: '{{ kibana_repo_name }} YUM repository'
    file: '{{ kibana_repo_name }}'
    baseurl: '{{ kibana_repo_url }}'
    gpgcheck: 'no'
    sslverify: 'no'
    timeout: '60'

- name: Install the Kibana packages.
  yum:
    name: '{{ kibana_packages }}'
    state: 'present'
    enablerepo: '{{ kibana_repo_name }}'
    validate_certs: 'no'
    update_cache: 'yes'
    disable_gpg_check: 'yes'
  register: kibana_update
  until: kibana_update is succeeded
  notify: 'Ensure Kibana service is enabled.'
  retries: 5
  delay: 2
