---
- name: Create Prometheus export user.
  uri:
    url: 'http://{{ kibana_servers[0] }}:{{ kibana_elastic_port }}/_xpack/security/user/prometheus'
    method: 'POST'
    user: '{{ kibana_user }}'
    password: '{{ kibana_pass }}'
    body: '{"password": "password", "roles": [ "monitoring_user" ], "full_name": "Prometheus"}'
    body_format: 'json'
    force_basic_auth: 'yes'
  environment:
    no_proxy: 'kibana_servers[0]'
  when:
    - kibana_auth | bool
    - kibana_servers[0] in ansible_default_ipv4.address
  register: kibana_prometheus_user_add_status
  until: kibana_prometheus_user_add_status.status == 200
  retries: 3
  delay: 3
  changed_when: false
  failed_when: false
  no_log: true

- name: Check register client are accessible from current host
  uri:
    url: '{{ consul_public_http_prot }}://{{ item }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'GET'
    timeout: '5'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ item }}'
  loop: '{{ consul_public_clients }}'
  changed_when: false
  failed_when: false
  register: check_consul_reg

- name: Register exporter service with an http health check
  uri:
    url: '{{ consul_public_http_prot }}://{{ item.client }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'PUT'
    body: '{"tags":["prometheus","exporter"],"ID":"{{ inventory_hostname | upper }}_kibana_exporter","name":"kibana_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ kibana_port_server }},"meta":{"metrics_path":"{% if kibana_proxy | bool %}/kibana{% endif %}/_prometheus/metrics","instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"{% if tags is defined %},{{ tags | to_json | regex_replace("{") | regex_replace("}") }}{% endif %}},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ kibana_port_server }}{% if kibana_proxy | bool %}/kibana{% endif %}/_prometheus/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"10s"}]}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Consul-Token: '{{ consul_public_exporter_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ item.client }}'
  loop: "{{ check_consul_reg.results | json_query('[*].{client:item,status:status}') }}"
  when:
    - item.status == 405
  register: register_status
  until: register_status.status == 200
  retries: 3
  delay: 3
  no_log: true
  changed_when: false
  failed_when: false
