---
- name: Ensure Kibana service is enabled.
  systemd:
    name: 'kibana.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0

- name: Ensure Kibana exporter service is enabled.
  systemd:
    name: 'kibana_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'