---
- name: Enable Kibana service
  systemd:
    name: 'kibana.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0
  listen: Ensure Kibana service is enabled
